export const projects = [
  {
    slug: 'nova',
    name: 'MIRAI NOVA',
    category: '企業・コーポレート',
    type: 'WEB DESIGN',
    image: 'machine',
    color: '#263b50',
    title: '技術のその先に、\n新しいあたりまえを。',
    description:
      '精密技術を扱う企業の、信頼感と先進性。事業別の切り替えから、会社案内・採用情報まで。',
    tags: ['事業紹介', '情報設計', '採用'],
    note: '事業メニューを選ぶと、紹介内容が切り替わります。',
  },
  {
    slug: 'lumina',
    name: 'LUMINA MIRAI',
    category: '美容室・サロン',
    type: 'MOTION DESIGN',
    image: 'fashion',
    color: '#a1826d',
    title: '似合う、の先へ。\n私らしさに出会う。',
    description:
      '余白、写真、やわらかな動き。カット・カラーのメニューと予約体験を備えたサロンサイト。',
    tags: ['スタイルギャラリー', 'メニュー', '予約デモ'],
    note: 'スタイルの切り替えや、予約フォームをお試しください。',
  },
  {
    slug: 'noir',
    name: 'TABLE 未来',
    category: '飲食店・レストラン',
    type: 'BRAND EXPERIENCE',
    image: 'dining',
    color: '#67533b',
    title: '季節を味わう。\n余韻を愉しむ。',
    description:
      '料理の細部、季節のコース、テーブルの予約。一晩の体験を丁寧に伝えるレストラン。',
    tags: ['コース切り替え', '店舗案内', '予約デモ'],
    note: 'ディナー・ランチを選ぶと、コース内容と料金が変わります。',
  },
  {
    slug: 'eclat',
    name: 'MAISON MIRAI',
    category: 'ファッション・ブランド',
    type: 'ART DIRECTION',
    image: 'bag',
    color: '#84664e',
    title: '日々に寄り添う、\nひとつの美しさ。',
    description:
      '素材の質感と形の美しさを主役に。色の選択から製品のディテールまで伝えるコレクション。',
    tags: ['製品セレクター', '素材の紹介', 'コレクション'],
    note: 'カラーを選んで、製品の表情の違いをご覧ください。',
  },
  {
    slug: 'luce',
    name: 'MIRAI HILLS 目黒',
    category: '不動産・分譲マンション',
    type: 'REAL ESTATE',
    image: 'hotel',
    color: '#a8844f',
    title: '光の高さで、\n暮らしを選ぶ。',
    description:
      '階数ごとの眺望を360°で比べ、Blenderで制作したモデルルームを歩いて内覧できる分譲マンションの販売サイト。',
    tags: ['眺望シミュレーション', '3Dモデルルーム', '間取り'],
    note: '5階・12階・20階を選んで眺望を比べ、「3Dで内覧する」でモデルルームを歩けます。',
  },
  {
    slug: 'aether',
    name: 'MIRAI ONE',
    category: 'プロダクト・3D',
    type: '3D EXPERIENCE',
    image: 'architecture',
    color: '#343f44',
    title: '音のかたちを、\nその手で確かめる。',
    description:
      '外装を開き、音の構造を覗く。スライダーで自由に分解・組み立てを楽しめる3D製品紹介。',
    tags: ['リアルタイム3D', '分解表示', '製品仕様'],
    note: '「外観・分解・内部」のボタンやスライダーで操作できます。',
  },
  {
    slug: 'casa',
    name: 'CASA MIRAI',
    category: '住宅・建築',
    type: 'ARCHITECTURE',
    image: 'house',
    color: '#798075',
    title: '光と、余白と、\n暮らしていく。',
    description:
      '建物の外観から、暮らしの内側へ。空間を回転し、視点と時間帯を切り替えられる住宅紹介。',
    tags: ['3D内覧', '昼夜切り替え', '間取り'],
    note: '「3Dで内覧する」から、外観・リビング・寝室を切り替えられます。',
  },
  {
    slug: 'room',
    name: 'THE MIRAI ROOM',
    category: '空間・バーチャル',
    type: 'VIRTUAL SPACE',
    image: 'studio',
    color: '#587365',
    title: '覗いて、触れて、\nつくり手を知る。',
    description:
      '小さなアトリエを舞台にしたポートフォリオ。道具を選ぶと、制作分野やストーリーが現れます。',
    tags: ['空間の探索', 'クリック操作', '3D'],
    note: '部屋のPC・カメラ・本棚・テレビを選んでください。',
  },
  {
    slug: 'yui',
    name: 'MIRAI TAKAHASHI',
    category: '写真・クリエイター',
    type: 'EDITORIAL DESIGN',
    image: 'hotel',
    color: '#897973',
    title: '何気ない日々の、\nまだ見ぬ表情。',
    description:
      '写真が語り、文字はそっと添える。作品の絞り込みと拡大表示ができる写真家のポートフォリオ。',
    tags: ['作品フィルター', '写真の拡大', 'プロフィール'],
    note: 'カテゴリーで絞り込み、写真をクリックして大きく表示できます。',
  },
  {
    slug: 'adapt',
    name: 'MIRAI / YOU',
    category: 'パーソナライズ',
    type: 'INTERACTIVE DESIGN',
    image: 'studio',
    color: '#516ee1',
    title: 'あなたの感性から、\nデザインが生まれる。',
    description:
      '色、書体、レイアウト、立体。選んだスタイルでページ全体が変わるインタラクティブな実験。',
    tags: ['5つのスタイル', '即時切り替え', 'WebGL'],
    note: '5つのスタイルを選ぶと、色・書体・3Dの表情が変わります。',
  },
  {
    slug: 'offgrid',
    name: 'OFF GRID みらい',
    category: 'イベント・キャンペーン',
    type: 'CAMPAIGN DESIGN',
    image: 'outdoors',
    color: '#df552d',
    title: 'いつもの外へ。\n自分に還る週末。',
    description:
      '山、音楽、食を楽しむ架空の野外イベント。日程を選び、体験プログラムとチケットを確認できます。',
    tags: ['日程切り替え', 'タイムテーブル', 'チケットデモ'],
    note: '日程を選んで、プログラムとチケット料金を確認できます。',
  },
];
export type Project = (typeof projects)[number];
