export const projects = [
  {
    slug: 'nova',
    name: 'MIRAI NOVA',
    category: '企業・コーポレート',
    type: 'WEB DESIGN',
    image: 'machine',
    color: '#263b50',
    title: '技術のその先に、\n新しいあたりまえを。',
    description:
      '精密技術を扱う企業の、信頼感と先進性。事業別の切り替えから、会社案内・採用情報まで。',
    tags: ['事業紹介', '情報設計', '採用'],
    note: '事業メニューを選ぶと、紹介内容が切り替わります。',
  },
  {
    slug: 'lumina',
    name: 'LUMINA MIRAI',
    category: '美容室・サロン',
    type: 'MOTION DESIGN',
    image: 'fashion',
    color: '#a1826d',
    title: '似合う、の先へ。\n私らしさに出会う。',
    description:
      '余白、写真、やわらかな動き。カット・カラーのメニューと予約体験を備えたサロンサイト。',
    tags: ['スタイルギャラリー', 'メニュー', '予約デモ'],
    note: 'スタイルの切り替えや、予約フォームをお試しください。',
  },
  {
    slug: 'noir',
    name: 'TABLE 未来',
    category: '飲食店・レストラン',
    type: 'BRAND EXPERIENCE',
    image: 'dining',
    color: '#67533b',
    title: '季節を味わう。\n余韻を愉しむ。',
    description:
      '料理の細部、季節のコース、テーブルの予約。一晩の体験を丁寧に伝えるレストラン。',
    tags: ['コース切り替え', '店舗案内', '予約デモ'],
    note: 'ディナー・ランチを選ぶと、コース内容と料金が変わります。',
  },
  {
    slug: 'eclat',
    name: 'MAISON MIRAI',
    category: 'ファッション・ブランド',
    type: 'ART DIRECTION',
    image: 'bag',
    color: '#84664e',
    title: '日々に寄り添う、\nひとつの美しさ。',
    description:
      '素材の質感と形の美しさを主役に。色の選択から製品のディテールまで伝えるコレクション。',
    tags: ['製品セレクター', '素材の紹介', 'コレクション'],
    note: 'カラーを選んで、製品の表情の違いをご覧ください。',
  },
  {
    slug: 'luce',
    name: 'MIRAI HILLS 目黒',
    category: '不動産・分譲マンション',
    type: 'REAL ESTATE',
    image: 'hotel',
    color: '#a8844f',
    title: '光の高さで、\n暮らしを選ぶ。',
    description:
      '階数ごとの眺望を360°で比べ、Blenderで制作したモデルルームを歩いて内覧できる分譲マンションの販売サイト。',
    tags: ['眺望シミュレーション', '3Dモデルルーム', '間取り'],
    note: '5階・12階・20階を選んで眺望を比べ、「3Dで内覧する」でモデルルームを歩けます。',
  },
  {
    slug: 'aether',
    name: 'MIRAI ONE',
    category: 'プロダクト・3D',
    type: '3D EXPERIENCE',
    image: 'architecture',
    color: '#343f44',
    title: '音のかたちを、\nその手で確かめる。',
    description:
      '外装を開き、音の構造を覗く。スライダーで自由に分解・組み立てを楽しめる3D製品紹介。',
    tags: ['リアルタイム3D', '分解表示', '製品仕様'],
    note: '「外観・分解・内部」のボタンやスライダーで操作できます。',
  },
  {
    slug: 'casa',
    name: 'CASA MIRAI',
    category: '住宅・建築',
    type: 'ARCHITECTURE',
    image: 'house',
    color: '#798075',
    title: '光と、余白と、\n暮らしていく。',
    description:
      '建物の外観から、暮らしの内側へ。空間を回転し、視点と時間帯を切り替えられる住宅紹介。',
    tags: ['3D内覧', '昼夜切り替え', '間取り'],
    note: '「3Dで内覧する」から、外観・リビング・寝室を切り替えられます。',
  },
  {
    slug: 'room',
    name: 'THE MIRAI ROOM',
    category: '空間・バーチャル',
    type: 'VIRTUAL SPACE',
    image: 'studio',
    color: '#587365',
    title: '覗いて、触れて、\nつくり手を知る。',
    description:
      '小さなアトリエを舞台にしたポートフォリオ。道具を選ぶと、制作分野やストーリーが現れます。',
    tags: ['空間の探索', 'クリック操作', '3D'],
    note: '部屋のPC・カメラ・本棚・テレビを選んでください。',
  },
  {
    slug: 'yui',
    name: 'MIRAI TAKAHASHI',
    category: '写真・クリエイター',
    type: 'EDITORIAL DESIGN',
    image: 'hotel',
    color: '#897973',
    title: '何気ない日々の、\nまだ見ぬ表情。',
    description:
      '写真が語り、文字はそっと添える。作品の絞り込みと拡大表示ができる写真家のポートフォリオ。',
    tags: ['作品フィルター', '写真の拡大', 'プロフィール'],
    note: 'カテゴリーで絞り込み、写真をクリックして大きく表示できます。',
  },
  {
    slug: 'adapt',
    name: 'MIRAI / YOU',
    category: 'パーソナライズ',
    type: 'INTERACTIVE DESIGN',
    image: 'studio',
    color: '#516ee1',
    title: 'あなたの感性から、\nデザインが生まれる。',
    description:
      '色、書体、レイアウト、立体。選んだスタイルでページ全体が変わるインタラクティブな実験。',
    tags: ['5つのスタイル', '即時切り替え', 'WebGL'],
    note: '5つのスタイルを選ぶと、色・書体・3Dの表情が変わります。',
  },
  {
    slug: 'offgrid',
    name: 'OFF GRID みらい',
    category: 'イベント・キャンペーン',
    type: 'CAMPAIGN DESIGN',
    image: 'outdoors',
    color: '#df552d',
    title: 'いつもの外へ。\n自分に還る週末。',
    description:
      '山、音楽、食を楽しむ架空の野外イベント。日程を選び、体験プログラムとチケットを確認できます。',
    tags: ['日程切り替え', 'タイムテーブル', 'チケットデモ'],
    note: '日程を選んで、プログラムとチケット料金を確認できます。',
  },
  {
    slug: 'drive',
    name: 'MIRAI MOTORS',
    category: '自動車販売・整備',
    type: 'AUTOMOTIVE',
    image: 'machine',
    color: '#1b2733',
    title: '夜の高速を、\nスクロールで走る。',
    description:
      'ページそのものが夜の高速道路。案内標識が在庫車・車検予約・買取査定への出口になる、町の車屋さんのサイト。',
    tags: ['在庫検索', 'ローン試算', '車検予約'],
    note: 'スクロールで加速し、標識の出口から各ページへ進めます。',
  },
  {
    slug: 'yaoya',
    name: 'やおや みらい',
    category: '個人商店・八百屋',
    type: 'LOCAL SHOP',
    image: 'restaurant',
    color: '#3d6b34',
    title: 'のれんをくぐって、\n今日の旬を。',
    description:
      '商店街の八百屋。のれんをくぐって入店し、店頭の野菜をかごに入れて取り置きを頼める、手ざわりのある個人商店サイト。',
    tags: ['今日の入荷', '取り置き', '営業日カレンダー'],
    note: 'のれんをめくって入店し、野菜をかごに入れてみてください。',
  },
  {
    slug: 'library',
    name: 'みらい市立図書館',
    category: '図書館・公共施設',
    type: 'PUBLIC LIBRARY',
    image: 'studio',
    color: '#5a3f2a',
    title: '一冊と出会う、\n本棚の検索。',
    description:
      '本棚そのものが検索窓。打ちこむたびに該当する本が棚から迫り出し、開いて予約まで進める市立図書館のサイト。',
    tags: ['蔵書検索', '開館カレンダー', 'イベント'],
    note: '検索欄に「猫」「宇宙」「料理」などを入れてみてください。',
  },
  {
    slug: 'city',
    name: '未来市役所',
    category: '自治体・役所',
    type: 'CIVIC DESIGN',
    image: 'architecture',
    color: '#1f5a94',
    title: '番号札をとれば、\n手続きが見える。',
    description:
      '用事を選んで番号札をとると、必要な手続きと窓口までの道順が出てくる市役所サイト。文字の大きさや、やさしい日本語にも一瞬で切り替わります。',
    tags: ['手続きナビ', 'やさしい日本語', '窓口の混雑'],
    note: '「番号札をとる」から、引っ越しや出産などの用事を選んでください。',
  },
  {
    slug: 'arc',
    name: 'MIRAI ARC',
    category: '自動車メーカー・新型車',
    type: 'AUTOMOTIVE 3D',
    image: 'machine',
    color: '#20262e',
    title: '触れて、開けて、\n乗りこむ新型車。',
    description:
      '架空の電気自動車の新型車サイト。3Dの車体を回して色を選び、ドアを開けて運転席に座れる。グレードと価格の試算から試乗予約まで。',
    tags: ['3Dコンフィギュレーター', '運転席に乗る', '試乗予約'],
    note: '車体をドラッグで回し、ドアに触れて開け、「乗りこむ」で運転席へ。',
  },
  {
    slug: 'goods',
    name: 'MIRAI GOODS',
    category: '通販・ECサイト',
    type: 'E-COMMERCE',
    image: 'studio',
    color: '#8a6a4a',
    title: '選んだ道具が、\n箱に詰まっていく。',
    description:
      '器や台所道具の通販サイト。カートは段ボール箱で、入れた品が箱に落ちて詰まり、箱の大きさと送料がその場で決まる。',
    tags: ['商品検索', '箱詰めカート', '購入手続き'],
    note: '商品を「かごに入れる」と、段ボール箱に詰まっていきます。',
  },
  {
    slug: 'games',
    name: 'MIRAI GAMES',
    category: 'ゲーム会社',
    type: 'GAME STUDIO',
    image: 'studio',
    color: '#1a1433',
    title: 'サイトそのものが、\n遊べる一本目。',
    description:
      'ゲーム会社の公式サイト。トップがそのまま遊べるゲームで、作品一覧はソフトのパッケージ、採用はキャラクター選択画面。',
    tags: ['遊べるトップ', 'タイトル一覧', '採用'],
    note: 'トップの画面はそのまま遊べます。キーボードかタップで操作してください。',
  },
];
export type Project = (typeof projects)[number];
